### ISSUE TITLE
[BUG] H2016/2 LOCR format unsupported

### ISSUE THREAD

**Issue by RDIL** [glacier-modding/RPKG-Tool#5]
**Describe the bug**

rpkg crashes when trying to open a H2016/2 LOCR file, most likely due to a different format.

**To Reproduce**
Try opening the dynamic resources.

**Expected behavior**
It unpacks without crashing.

**RPKG tool version:** 2.14

**Hitman Version:** 2016 steam

**Comment by AnthonyFuller** [comment]
Fixed in https://github.com/glacier-modding/RPKG-Tool/commit/7688224a217cd4b73ddbde69c70e866c4e8d00b3 you can use the artifacts from the actions workflow [here](https://github.com/glacier-modding/RPKG-Tool/actions/runs/1005967157) until the next release.

Will close when an actual release has been made.

**Comment by AnthonyFuller** [comment]
Added support for other version (10 languages) in 99f4dd9.

Fixes were pushed in [v2.16.2](https://github.com/glacier-modding/RPKG-Tool/releases/tag/v2.16.2).

Thanks for the report. Closing.
